### ISSUE TITLE
Issue sending pdf file

### ISSUE THREAD

**Issue by ksenechal** [seeuletter/seeuletter-node#9]
Hi there,

I got an error using the seeuletter-node when sending a pdf file. I spend a lot of time to find why I got it without success. Maybe you'll have an idea or meet already this issue.

Thank you !

Here is the stacktrace  : 

` TypeError: Cannot read properties of null (reading 'name')
at FormData._getContentDisposition (/home/app/node_modules/form-data/lib/form_data.js:226:40)
 at FormData._multiPartHeader (/home/app/node_modules/form-data/lib/form_data.js:177:33)
at FormData.append (/home/app/node_modules/form-data/lib/form_data.js:70:21)
at appendFormValue (/home/app/node_modules/request/request.js:326:21)
at Request.init (/home/app/node_modules/request/request.js:337:11)
at new Request (/home/app/node_modules/request/request.js:127:8)
at request (/home/app/node_modules/request/index.js:53:10)
at /home/app/node_modules/seeuletter/lib/resources/resourceBase.js:74:7
at Promise._execute (/home/app/node_modules/bluebird/js/release/debuggability.js:384:9)
 at Promise._resolveFromExecutor (/home/app/node_modules/bluebird/js/release/promise.js:518:18)
at new Promise (/home/app/node_modules/bluebird/js/release/promise.js:103:10)
at Letters._transmit (/home/app/node_modules/seeuletter/lib/resources/resourceBase.js:73:12)
at Letters.create (/home/app/node_modules/seeuletter/lib/resources/letters.js:35:17)
`

and the content of the request payload : 
`{
     description: "PV de l'assemblée générale du 02/03/2023",
     from: {
       company: 'Test',
       address_line1: '10 rue du test',
       address_line2: '',
       address_city: 'Paris',
       address_country: 'France',
       address_postalcode: '75000'
     },
     to: {
       name: 'Test',
       address_line1: '3 rue du test',
       address_line2: '',
       address_city: 'Paris',
       address_country: null,
       address_postalcode: '75000'
     },
     postage_type: 'lrar',
     color: 'bw',
     source_file: <Buffer 25 50 44 46 2d 31 2e 34 0a 25 d3 eb e9 e1 0a 31 20 30 20 6f 62 6a 0a 3c 3c 2f 43 72 65 61 74 6f 72 20 28 43 68 72 6f 6d 69 75 6d 29 0a 2f 50 72 6f 64 ... 194599 more bytes>,
     source_file_type: 'file'
   }`

The buffer value is built with : 
`let file = Buffer.from(fileContent)`

**Comment by ksenechal** [comment]
The given address_country was null, it was causing the issue.
